version: 2
jobs:
  build:
    working_directory: ~/financial-planning
    docker:
      - image: circleci/node:14.2.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Build
          command: npm run build
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Run Lint
          command: npm run lint
  deploy:
    steps:
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
